### ISSUE TITLE
yarn.lock error

### ISSUE THREAD

**Issue by joaomilho** [rxdi/firelink#10]
My deployment fails with 

```
error Your lockfile needs to be updated, but yarn was run with \`--frozen-lockfile\`.
```

I assume it's because firelink changes my package without running install again and firebase runs it with --frozen-lockfile, which disallows changes in the lock file.

So, I wonder, if that's the case, how come you don't have this issue too?

Thanks!

**Comment by nk1tz** [comment]
I've run into the same.

**Comment by Stradivario** [comment]
@nk1tz

Thanks for writing the last comment for some reason i miss the email with notification for this issue.

Looking forward to this issue and today i will release a patch.

Regards,
Kristiyan Tachev

**Comment by nk1tz** [comment]
Very cool, thank you!

**Comment by Stradivario** [comment]
@nk1tz @joaomilho issue should be resolved in 0.7.54!

I have removed `yarn.lock` from dependencies since we can use `package-lock.json` instead.

Added automatic deploy and publish when we merge change to master 

Added `CHANGELOG.md` using `conventional commit strategy`  https://github.com/rxdi/firelink/blob/master/CHANGELOG.md

Updated the documentation inside `README.md` since this library can be installed as a stand alone library without `nodejs`

More info can be found here

https://github.com/rxdi/firelink/pull/12


Please reopen if needed.

Regards,
Kristiyan Tachev

**Comment by Stradivario** [comment]
I just re-read again the issue and it seems like this is some different bug. I will try Test deployment using firebase cli in order to track whats changed and how to mitigate it. 

Anyway these fixes above where long time wanted so i am happy that i commit them :))

Cheers!

**Comment by nk1tz** [comment]
The full error as reported in firebase functions logs:
The error is logged once for every function that is deployed.

```
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"Build failed: yarn install v1.22.4\n[1/5] Validating package.json...\n[2/5] Resolving packages...\nerror Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.; Error ID: 98e389b6"},...
```

**Comment by Stradivario** [comment]
@nk1tz Hey man do you still have the same problem ? 

Please reopen this ticket if you do so :) 

Cheers!
