### ISSUE TITLE
npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by X-Titouan** [rxdi/firelink#18]
Hey mate,

I tryed to deloy a function with a local dependency since a week now, i'm going CRAZY !

Your package since to be nice but when I do firelink deploy, I get this error:

```
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/XXXX/.npm/_logs/2021-09-21T12_02_49_871Z-debug.log
true
```

Is there something you know how to fix ? 

Here is my package.json :

```
{
  "name": "api",
  "main": "build/index.js",
  "scripts": {
    "build": "tsc",
  },
  "engines": {
    "node": "14"
  },
  "dependencies": {
    "core": "file:../core",
    ...
  },
  "devDependencies": {
    ...
  },
  "fireDependencies": {
    "core": "../core"
  },
  "private": true,
  "fireConfig": {
    "runner": "./"
  }
}
```

Here is my repo:

![Capture d’écran du 2021-09-21 14-09-56](https://user-images.githubusercontent.com/85634633/134168010-284a11c6-a310-48ad-812e-48949d121c65.png)

And core is here :

- packages
    - api_firelink
    - core

Can you explain me what exactly does your firelink deploy ?

Save me, my brain is melting please

**Comment by Stradivario** [comment]
hahahahahahahaha @X-Titouan

Happy to help you mate! :D 

First of all i can see that you have specified `runner` property inside package.json and i see that you provide a runner `./` so i assume this is what causes the issue. 

Remove fireConfig or put `firebase` or `gcloud` in the runner property.

The main idea behind firelink is simple 

1. You have a local npm packages or private packages that you want to deploy
2. To deploy it as a lambda you have 2 options either you need to bundle it as single js file or you can work with node_modules folder without bundle them
3. Firelink relies on the existing feature of npm to install packages locally just like you install them from `npm` registry
4. So before deploying the application it will copy packages in temporary folder and then it will install them as an npm packages inside the bundle.
5. So when you try to execute `firebase deploy` you need to predefine the packages so they can be installable and it is a repetative job to redefine package.json every time you want to deploy something. Firelink makes it possible by wrapping command `firebase` so when you execute `firelink deploy` it will make everything for you

Since i am working at the moment i will be happy to help you on share screen later and to help you with your use case how is this sounds to you ?


I will be available here at hangouts https://hangouts.google.com/call/Rw2EICWR8jlmEXe-Qj2UAEEI

I have a spare time in about 1 hour and after 3 hours again.

**Comment by X-Titouan** [comment]
You are the light in the darkenesses ! 

I will be on hangout at 7:30 pm UTC +2 then !

**Comment by Stradivario** [comment]
hahaha @X-Titouan it says you are not allowed to join this call :D 

I am so sorry but i have another meeting in 15 minutes so we need to be fast

https://meet.google.com/wqo-mhug-kjr?authuser=0

I have created a google meet one

Regards!

**Comment by Stradivario** [comment]
![image](https://user-images.githubusercontent.com/19847933/134229179-18e2e72f-2255-4ba6-a0ec-2bd315714b67.png)

Unfortunate :( 

I can see that you are inside the meeting but it doesn't let me enter it
![image](https://user-images.githubusercontent.com/19847933/134229548-0b5f2385-1637-4236-b159-a58b59030b88.png)

**Comment by Stradivario** [comment]
So sorry man i need to go feel free to contact me kristiqn.tachev@gmail.com we can invite each other and create Google Calendar Meeting

I am available tomorrow from 1 CT to 12 CT  since i am from Bulgaria i get up at 09:00 and i am available till 20:00. 

Set a meeting and i will enter it :))

Regards and have a great day/evening!

**Comment by X-Titouan** [comment]
I sent you an email :)

When would you be disponible for a quick call ?

**Comment by Stradivario** [comment]
I am closing this issue since it was not related to the firelink itself and more to the way that the actual project was setup.

Please feel free @X-Titouan to open another ticket if you have a problem :)) 

Regards
