### ISSUE TITLE
Remove created dir on finish/error?

### ISSUE THREAD

**Issue by ftzi** [rxdi/firelink#46]
The generated dir is causing me some issues on local dev env. It would be good if it was automatically removed or we have a flag to do it. For now I will `|| true && rm .firelink` (my outFolderName).

**Comment by Stradivario** [comment]
So actually there is no `.firelink` folder there is only `.packages`. Maybe you change the folder name ? 

Actually the `.packages` folder or in your case `.firelink` is something that needs to stay in the directory since the code will be deployed with it. 

What is your case ? 

Give some more details like 

1. Paste your configuration here 
2. Explain more about why do you need to remove this directory ?
3. What issues is causing the generated directory ?
4. If you have some problem with it why don't you use `.gitignore` ?

What i can do is a command called `--clean` for example which will delete all the artifacts created by the library.

Sorry without further more details i cannot do anything to help you. 

Regards,
Kristiyan Tachev

**Comment by ftzi** [comment]
Hi @Stradivario !

Yes, indeed I have changed the directory name, as I mentioned in the post.

I know that the generated directory is vital for the deploy, but on dev, they actually cause me two issues (and they are special cases):

1) My frontend imports from firebase/functions. Not actual executable code, but just types. When the .firelink | .packages dir is present, I can't build my frontend due to some strange errors. I delete it, and I can build it.

2) I have strange TS errors using a specific package on functions when the .firelink dir is there. The package in question (typesaurus) has some deep TS magics, but the error is caused by an unknown TS bug. The types are exactly the same, but the shady TS error happens. I remove the .firelink dir, it works back again.

.gitignore wouldn't change my issue.

The --clean would suit me very well. The .packages dir would only exist on deploy.

**Comment by ftzi** [comment]
Just for your info, I decided to name it as .firelink because certainly I would forget what the .packages means in the future. Also, it's easier for someone else to catch it up.

Edit: and also, many thanks for your quick reply and kind response!

**Comment by Stradivario** [comment]
@SrBrahma

Sounds to me that your problem is somewhere else and if you have time we can make a call to share your screen and to help you resolve the issues.

I don't think that one folder should break the whole application and bundle. I think you need to exclude some files from bundling. 

My email is kristiqn.tachev@gmail.com feel free to create Google Calendar Meeting to discuss your problem. 

`--clean` option is nice to have and i will introduce a PR with it but i think we are fixing in your case the side effect from wrong bundle configuration .

**Comment by Stradivario** [comment]
I have created a ticket for introducing `--clean` option

https://github.com/rxdi/firelink/issues/52

Please feel free to re open the ticket if you do need some help :) 

Cheers
