### ISSUE TITLE
0.9.2 broke deployment

### ISSUE THREAD

**Issue by WesleyYue** [rxdi/firelink#70]
I tried to read the commits since 0.9.1 but I'm not sure what cause this. Using 0.9.2, I get the following in the google cloud logs:

```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@mynamespace/mypackage'
```

**Comment by Stradivario** [comment]
I don't know why but for some reason the beta version is installing when i try to run `npm i -g @rxdi/firelink` It should get 0.9.2 but instead it gets 1.0.0-beta-1 which is odd. 

Let me remove all of the beta versions from npm and i am pretty sure everything will be ok.

**Comment by Stradivario** [comment]
@WesleyYue i have unpublished beta versions for now and 0.9.2 version is the correct one and you should not have any problems.

Please verify and write down again here.

Thanks!

**Comment by Stradivario** [comment]
It appears that i have published the beta version wrong instead of `@rxdi/firelink@1.0.0-beta-1` i should of do `@rxdi/firelink@1.0.0-beta.1` 

Using dot instead of dash...

This caused every build in the process to get latest version which is the beta one instead of the production ready one which is 0.9.2...

Sorry for the caused failed builds..
